name: Build iOS IPA
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Flet
        run: pip install flet

      - name: Build App
        run: |
          # Флаг --yes говорит "да" на все вопросы установщика
          flet build ipa --yes
          
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: my-ios-app
          path: build/ipa/*.ipa
