name: Build iOS IPA
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # Устанавливаем самую свежую версию flet, где эта ошибка исправлена
          pip install --upgrade flet httpx requests

      - name: Setup Flutter
        # Явно устанавливаем Flutter, чтобы Flet не пытался скачать его сам
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build App Bundle
        run: |
          # Запускаем сборку. Если упадет с 'unicode', флаг --verbose покажет где именно
          flet build ipa --yes --product "llorTStore" --org com.p4.llorTStore --verbose

      - name: Create TrollStore IPA
        # Для TrollStore нужно просто положить .app в папку Payload и зазиповать
        run: |
          mkdir -p Payload
          # Ищем собранный .app и копируем его
          cp -r build/**/*.app Payload/
          zip -r llorTStore.ipa Payload
                    
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: llorTStore-TrollStore
          path: llorTStore.ipa
          if-no-files-found: error
