name: Build iOS IPA
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install flet
          # Если используешь другие библиотеки, добавь их сюда

      - name: Build App
        run: |
          # Собираем только структуру приложения
          flet build ipa --no-copy-itunes-artwork --no-version-check

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: my-ios-app
          path: build/ios/iphoneos/*.app
